apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: velero-binding
  namespace: velero
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: velero
subjects:
  - kind: ServiceAccount
    name: velero
    namespace: velero
