apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: restic
  namespace: velero
  labels:
    component: velero
spec:
  selector:
    matchLabels:
      name: restic
  template:
    metadata:
      labels:
        name: restic
        component: velero
    spec:
      serviceAccountName: velero
      containers:
      - name: restic
        image: velero/velero:v1.9.0
        command:
          - /velero
        args:
          - restic
          - server
        securityContext:
          runAsUser: 0
          privileged: true
        volumeMounts:
        - mountPath: /host_pods
          name: host-pods
          mountPropagation: Bidirectional
        env:
        - name: VELERO_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumes:
      - name: host-pods
        hostPath:
          path: /var/lib/kubelet/pods
          type: Directory
