apiVersion: v1
kind: Secret
metadata:
  name: velero
  namespace: velero
type: Opaque
stringData:
  AZURE_SUBSCRIPTION_ID: xxxxxxxxxxxxxxx
  AZURE_TENANT_ID: xxxxxxxxxxxxxxx
  AZURE_CLIENT_ID: xxxxxxxxxxxxxxx
  AZURE_CLIENT_SECRET: xxxxxxxxxxxxxxx

#AZURE_SUBSCRIPTION_ID: Encontre na seção "Assinaturas" no Portal do Azure.
#AZURE_TENANT_ID: Encontre na seção "Propriedades" do Azure Active Directory.
#AZURE_CLIENT_ID: Encontre na seção "Registros de aplicativos" do Azure Active Directory.
#AZURE_CLIENT_SECRET: Gere e obtenha na seção "Certificados e segredos" do Azure Active Directory.