apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-backup
  namespace: velero
spec:
  schedule: "0 15 * * *"
  template:
    ttl: 744h
    includedNamespaces:
      - "*"
    storageLocation: default
