apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero
  namespace: velero
spec:
  replicas: 1
  selector:
    matchLabels:
      component: velero
  template:
    metadata:
      labels:
        component: velero
    spec:
      serviceAccountName: velero
      initContainers:
        - name: velero-plugin-for-azure
          image: velero/velero-plugin-for-microsoft-azure:v1.5.0
          volumeMounts:
            - mountPath: /target
              name: plugins
      containers:
        - name: velero
          image: velero/velero:v1.9.0
          command:
            - /velero
          args:
            - server
          env:
            - name: AZURE_SUBSCRIPTION_ID
              value: xxxxxxxxxxxxxx
            - name: AZURE_TENANT_ID
              value: xxxxxxxxxxxxxx
            - name: AZURE_CLIENT_ID
              value: xxxxxxxxxxxxxx
            - name: AZURE_CLIENT_SECRET
              value: xxxxxxxxxxxxxx
          volumeMounts:
            - mountPath: /plugins
              name: plugins
            - name: velero-config
              mountPath: /etc/velero
      volumes:
        - name: velero-config
          configMap:
            name: velero
        - name: plugins
          emptyDir: {}
